version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: spectra_db
      POSTGRES_USER: tema
      POSTGRES_PASSWORD: tema
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "10300:5432"